spring:
  application:
    name: Spring-Ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3:8b

      logging:
        level:
          org.springframework.ai: DEBUG